import type { NextPage } from "next";
import Head from "next/head";
import Content from "./components/Content";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Surya Kumara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        <Content />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
